In [1]:
import numpy as np

Ejercicio 4. Resultados académicos


In [6]:

notas = np.array([[14, 16, 13, 15], 
                  [18, 17, 16, 19], 
                  [11, 13, 12, 14], 
                  [16, 15, 17, 16], 
                  [13, 10, 15, 12]]) 
puntajes_total=notas.sum(axis=1)
print(puntajes_total)

promedio=notas.mean(axis=1)
print(promedio)

promedio_sin_mean= puntajes_total /  notas.shape[1]
print(promedio_sin_mean)
print("="*100)
mejor_estudiante= promedio.argmax()+1
print(mejor_estudiante)
print("="*100)
puntaje_total_materia=notas.sum(axis=0)
print(puntaje_total_materia)

[58 70 50 64 50]
[14.5 17.5 12.5 16.  12.5]
[14.5 17.5 12.5 16.  12.5]
2
[72 71 73 76]


Ejercicio 5. Pasajeros por ruta y día

In [7]:
pasajeros = np.array([[120, 135, 128, 142, 150, 180, 175], 
                      [95, 102, 110, 108, 115, 130, 125], 
                      [160, 155, 170, 168, 172, 190, 185], 
                      [80, 88, 92, 100, 105, 118, 112]]) 

In [8]:
total_semanal_por_ruta=pasajeros.sum(axis=1)
print(total_semanal_por_ruta)

total_pasajeros_por_dia=pasajeros.sum(axis=0)
print(total_pasajeros_por_dia)

[1030  785 1200  695]
[455 480 500 518 542 618 597]
